[package]
name = "domains-event"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
libs-paging = { workspace = true }
libs-clock = { workspace = true }
libs-modeling = { workspace = true}

uuid = { workspace = true }
chrono = { workspace = true }
async-trait = { workspace = true }
